name: Deploy to EC2

on:
    push:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: "Checkout Source"
            uses: actions/checkout@v4

          - name: "Create .env file"
            run: echo "PORT=${{secrets.SERVER_PORT}}" >> .env

          - name: "Login to docker hub"
            run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}} 

          - name: "Build docker image"
            run: docker build -t priyanshu00268/quiz_app-server .

          - name: "Push Image to docker hub"
            run: docker push priyanshu00268/quiz_app-server:latest

    deploy:
        needs: build
        runs-on: self-hosted
        steps:
          - name: "Pull docker image"
            run: sudo docker pull priyanshu00268/quiz_app-server:latest

          - name: "Delete old container"
            run: sudo docker rm -f quiz-app-container

          - name: "Run docker container"
            run: sudo docker run -e SERVER_PORT=${{secrets.SERVER_PORT}} -e DB_PORT=${{secrets.DB_PORT}} -e DB_NAME=${{secrets.DB_NAME}} -e DB_USER=${{secrets.DB_USER}} -e DB_PASSWORD=${{secrets.DB_PASSWORD}} -e HOST=${{secrets.HOST}} -d -p 3001:3001 --name quiz-app-container priyanshu00268/quiz_app-server